name: RestingBlocks
version: 1.0
author: JaniDJ
main: de.janisworld.restingblocks.RestingBlocks
depend: []
commands:
  addRest:
    usage: /addRest
    permission: restingblocks
  delRest:
    usage: /delRest
    permission: restingblocks
permissions:
  restingblock:
    default: op